version: "2.24.5"
services:
  gecom-frontend:
    build: .
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: gecom-angular

  # Pour le développement (optionnel)
  gecom-dev:
    build: .
    ports:
      - "4201:80"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start -- --host 0.0.0.0 --port 4201
    environment:
      - NODE_ENV=development
