name: SonarCloud + Build Angular

on:
  push:
    branches:
      - feature/CG-4-feat-product-view-page
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm" # ✅ AJOUTER LE CACHE

      - name: Clean npm cache
        run: npm cache clean --force # ✅ NETTOYER LE CACHE

      - name: Install dependencies with npm mirror
        run: |
          # Utiliser le registry mirror Chinois (très fiable)
          npm config set registry https://registry.npmmirror.com
          npm install --legacy-peer-deps --prefer-offline

      - name: Run Jest tests with coverage
        run: npm run test:coverage

      - name: Build Angular app
        run: npm run build -- --configuration production
